# Generated by Django 3.1.3 on 2020-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('vendor_street', models.CharField(blank=True, max_length=100)),
                ('vendor_city', models.CharField(blank=True, max_length=100)),
                ('vendor_state', models.CharField(blank=True, max_length=100)),
                ('vendor_zip', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.CharField(blank=True, max_length=100)),
                ('due_date', models.CharField(blank=True, max_length=100)),
                ('amount_due', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
